[workspace]

resolver = "2"

members = [
    "sdk",
    "uniffi-bindgen",
]

[patch.'https://github.com/rust-lang/crates.io-index']
pqcrypto-internals = { git = 'https://github.com/vaf-hub/pqcrypto', rev = 'ffbce29b21665135e0d3fadc120bd04f079829a8' }